# Generated by Django 4.2.1 on 2023-05-22 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('has_parent', models.CharField(choices=[('hasM', 'hasMother'), ('hasF', 'hasFather'), ('non', 'noParent')], max_length=4)),
                ('singularity', models.CharField(max_length=4)),
                ('number_of_sons', models.IntegerField()),
                ('number_of_daughters', models.IntegerField()),
                ('number_of_common_brothers', models.IntegerField()),
                ('number_of_common_sisters', models.IntegerField()),
                ('number_of_brothers_from_father', models.IntegerField()),
                ('number_of_sister_from_father', models.IntegerField()),
                ('number_of_brothers_from_mother', models.IntegerField()),
                ('number_of_sisters_from_mother', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
