# Generated by Django 4.2.1 on 2023-05-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0002_remove_calculation_has_parent_calculation_has_father_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='singularity',
            field=models.CharField(choices=[('sing', 'single'), ('hasW', 'hasWife'), ('hasH', 'hasHusband')], max_length=4),
        ),
    ]
