# Generated by Django 4.2.1 on 2023-05-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0004_alter_calculation_number_of_brothers_from_father_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='number_of_sisters_from_mother',
            field=models.IntegerField(default=0, verbose_name=range(0, 10)),
        ),
    ]
