# Generated by Django 4.2.1 on 2023-07-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0010_alter_calculation_father_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='bro_of_dad_share',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calculation',
            name='bro_of_mom_share',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calculation',
            name='brother_share',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calculation',
            name='daughter_share',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calculation',
            name='hamsar_share',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calculation',
            name='mother_share',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calculation',
            name='sis_of_dad_share',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calculation',
            name='sis_of_mom_share',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calculation',
            name='sister_share',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calculation',
            name='son_share',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='father_share',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
