# Generated by Django 4.2.1 on 2023-07-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0011_calculation_bro_of_dad_share_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=1),
        ),
    ]
