# Generated by Django 4.2.1 on 2023-08-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0012_calculation_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='has_grandFather_of_father',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='calculation',
            name='has_grandFather_of_mother',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='calculation',
            name='has_grandMother_of_father',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='calculation',
            name='has_grandMother_of_mother',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1),
        ),
    ]
