# Generated by Django 4.2.1 on 2023-08-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0013_calculation_has_grandfather_of_father_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='father_of_father_share',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calculation',
            name='father_of_mother_share',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calculation',
            name='mother_of_father_share',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calculation',
            name='mother_of_mother_share',
            field=models.FloatField(default=0),
        ),
    ]
