# Generated by Django 4.2.1 on 2023-08-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0015_calculation_brother_from_father_share_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='bro_of_dad_share',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='bro_of_mom_share',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='brother_from_father_share',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='brother_from_mother_share',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='brother_share',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='daughter_share',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='father_share',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='hamsar_share',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='mother_share',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='sis_of_dad_share',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='sis_of_mom_share',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='sister_from_father_share',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='sister_from_mother_share',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='sister_share',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='son_share',
            field=models.FloatField(default=0),
        ),
    ]
